version: "3.8"
services:
  # db:
  #   image: postgres:13
  #   # volumes:
  #   #   - ./data/db:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=postgres
  #   ports:
  #     - "5432:5432"

  backend:
    image: backend:latest
    ports:
      - "5000:5000"
