version: '3.8'

services:
  backend:
    build:
      context: ../backend
    ports:
      - "5000:5000"
    networks:
      - mynetwork

  frontend:
    build:
      context: ../frontend
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    depends_on:
      - backend

networks:
  mynetwork:
    driver: bridge