version: '3.8'
services:
  desafio-murabei-frontend:
    build:
      context: ../02__frontend/codes/
    volumes:
      - ../02__frontend/codes:/app
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development

  desafio-murabei-backend:
    build:
      context: ../01__backend/codes/
    volumes:
      - ../01__backend/codes/:/app
      - ./data/db.sqlite:/app/db.sqlite
    command: flask run --host=0.0.0.0
    ports:
      - "8000:5000"
    environment:
      NODE_ENV: development
